### ISSUE TITLE
Feature Request: Add programming assignments w/ solutions

### ISSUE THREAD

**Issue by gkong88** [kirbs-/edX-Learning-From-Data-Solutions#22]
Hey All.

Feature request, is it possible to add on the corresponding programming assignments with the solutions? The edx course has been taken down and the AML site (https://work.caltech.edu/telecourse.html) only contains the book homework problems and not the projects.

Thanks,
-George

**Comment by kirbs-** [comment]
In the actual course it was up to the student to create their own implementation from scratch. There was no help. The homeworks are at https://work.caltech.edu/homeworks.html
